### PR TITLE
Add 'using namespace std' where appropriate

### PR DESCRIPTION
**Pull request by rye**
This fixes a number of compilation errors which occur (at least for me) on OS X.

### CODE REVIEW

**Comment by hawkrives** [comment]
Hi @rye! Can you try master now? I had a local commit that finished removing the need for `using namespace`, but I hadn't pushed it. 😢 

(That is, `master` @ 036529ffc8efd9554c2f8815e3a162ad9a1a3d36)

**Comment by rye** [comment]
Sure! I'll fetch master and give it a check.

**Comment by rye** [comment]
Yep, that fixed it.  I'll close this PR.

**Comment by hawkrives** [comment]
Thanks! Sorry about that.

**Comment by rye** [comment]
No problem!

**Pull request closed without merging**
